# Module 02 Homework - Pandas
Using a dataset from _Wine Spectator_, a wine magazine, we will practice the material that we covered in notebook M02_Colab04 to M02_Colab06. This notebook will cover data transformation, grouping, and sorting using pandas.

Created by JULIE NGUYEN (015783807)  
Last updated: 02/22

In [2]:
csvurl="https://gist.githubusercontent.com/clairehq/" + \
        "79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv"
import pandas as pd
wine = pd.read_csv(csvurl)

**Data cleaning**  
Notice that the first column is redundant. Part of data analysis is cleaning and removing redundancy. How would you drop the redundant column inplace, that is overwrite the dataframe.

#### Question 1: ####  
What is the mean of the points column?

In [3]:
wine["points"].mean()

np.float64(88.43403716087269)

#### Question 2: ####  
How many countries are present in this dataset? (Only count each country once)

In [4]:
# Your code here . . .
wine.head()
wine['country'].nunique()

41

#### Question 3: ####
How many times does each country appeared in this dataset? Show each country and the corresponding count (show counts in ascending order)

In [9]:
# Your code here . . .
wine['country'].value_counts().sort_values()

country
Slovakia                      1
Bosnia and Herzegovina        1
Armenia                       1
Luxembourg                    4
Switzerland                   4
India                         4
Ukraine                       5
Czech Republic                6
Macedonia                     6
Cyprus                        6
Serbia                        7
Peru                          8
Morocco                      11
Lebanon                      20
Moldova                      30
Brazil                       31
Mexico                       31
England                      36
Georgia                      37
Slovenia                     39
Turkey                       43
Croatia                      44
Uruguay                      61
Hungary                      61
Romania                      67
Bulgaria                     68
Canada                      108
Greece                      242
Israel                      259
New Zealand                 733
South Africa                737
Germany                    1051
Australia                  1177
Austria                    1635
Argentina                  1907
Chile                      2258
Portugal                   2963
Spain                      3409
Italy                     10005
France                    11174
US                        27177
Name: count, dtype: int64

#### Question 4: ####
Create a variable `adjusted_price` containing the adjusted price which is the price subtracted by the average price. *This is called **"centering" transformation** - a method commonly used in the preprocessing step before applying various machine learning algorithms.*

In [8]:
# Your code here . . .

average_price = wine["price"].mean()
wine["adjusted_price"] = wine["price"] - average_price
wine.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,adjusted_price
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,-20.232932
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,-21.232932
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,-22.232932
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,29.767068

#### Question 5: ####
What is the title of the wine that has the highest points-to-price ratio in the dataset?

In [12]:
# Your code here . . .

wine = wine.dropna(subset=["price"])

wine["ratio"] = wine["points"] / wine["price"]

wine[wine["ratio"] == wine["ratio"].max()]["title"]

64590    Bandit NV Merlot (California)
Name: title, dtype: object

#### Question 6: ####
Create a series `flavor_counts` that contains two values: the number of wines that has the word "tart" in the `description` column and the number of wines that has the word "berries" in the `description` column. The index of the Series should be "Tart" and "Berries" for the corresponding values.

In [14]:
# Look for the word "tart", not case sensitive, not a substring of another word.
# Same applies to the word "berries"
# Your code here . . .

import pandas as pd

tart = wine["description"].str.contains("tart", case=False, na=False).sum()
berries = wine["description"].str.contains("berries", case=False, na=False).sum()
flavor_counts = pd.Series([tart,berries], index=["Tart", "Berries"])
flavor_counts

Tart       4321
Berries    3370
dtype: int64

#### Question 7: ####
Let's convert the points into simple star ratings. A score of 90 or higher counts as 3 stars, a score of at least 80 but less than 90 is 2 stars. Any other score is 1 star.

Also, any wines from France should automatically get 3 stars, regardless of points.

Add this new column `star_ratings` to the dataframe with the number of stars for each wine in the dataset.

In [16]:
# Your code here . . .

wine["star_ratings"] = 1

wine.loc[(wine["points"] >= 80) & (wine["points"] < 90), "star_ratings"] = 2

wine.loc[wine["points"] >= 90, "star_ratings"] = 3

wine.loc[wine["country"] == "France", "star_ratings"] = 3

wine.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,adjusted_price,ratio,star_ratings
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,-20.232932,5.800000,2
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,-21.232932,6.214286,2
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,-22.232932,6.692308,2
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,29.767068,1.338462,2
5,5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem,-20.232932,5.800000,2

#### Question 8: ####
Who are the most common wine reviewers in the dataset? Create a Series whose index is the taster_twitter_handle category from the dataset, and whose values count how many reviews each person wrote.

In [17]:
# Your code here . . .

review_counts = wine["taster_twitter_handle"].value_counts()

review_counts

taster_twitter_handle
@vossroger          10296
@wineschach          7660
@kerinokeefe         4867
@paulgwine           4829
@vboone              4683
@mattkettmann        2992
@JoeCz               2539
@wawinereport        2336
@gordone_cellars     2029
@AnneInVino          1622
@laurbuzz             836
@suskostrzewa         589
@worldwineguys        459
@bkfiona               11
@winewchristina         4
Name: count, dtype: int64

#### Question 9: ####
What combination of countries and varieties are most common? Create a Series whose index is a MultiIndexof {country, variety} pairs. For example, a pinot noir produced in the US should map to {"US", "Pinot Noir"}. Sort the values in the Series in descending order based on wine count.

In [18]:
# Your code here . . .
country_variety_counts = wine.groupby(["country", "variety"]).size().sort_values(ascending=False)

country_variety_counts

country  variety
US       Pinot Noir                  4906
         Cabernet Sauvignon          3632
         Chardonnay                  3400
Italy    Red Blend                   1672
France   Bordeaux-style Red Blend    1613
                                     ...
Italy    Pignoletto                     1
         Rebo                           1
         Shiraz                         1
         Sémillon                       1
Uruguay  Tempranillo-Tannat             1
Length: 1278, dtype: int64

#### Question 10 #####
Create a Series whose index is reviewers and whose values is the average score given out by that reviewer.  
*Hint:* You will need the `taster_name` and `points` columns.

In [21]:
# Your code here . . .

reviewer_avg_scores = wine.groupby("taster_name")["points"].mean()
reviewer_avg_scores

taster_name
Alexander Peartree    86.014423
Anna Lee C. Iijima    88.367077
Anne Krebiehl MW      90.645499
Carrie Dykes          86.613636
Christina Pickard     89.500000
Fiona Adams           87.090909
Jeff Jenssen          88.273504
Jim Gordon            88.604239
Joe Czerwinski        88.523041
Kerin O’Keefe         88.884323
Lauren Buzzeo         87.533493
Matt Kettmann         90.046123
Michael Schachner     86.904047
Mike DeSimone         89.040000
Paul Gregutt          89.100849
Roger Voss            88.588869
Sean P. Sullivan      88.666524
Susan Kostrzewa       86.415959
Virginie Boone        89.234465
Name: points, dtype: float64